version: '3.5'
services:
  db-catalog:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Pr0duct0s12
    volumes:
      - mongo-data:/data/db
  catalog-ws:
    image: catalog-ws
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:7000
    depends_on:
      - db-catalog
volumes:
  mongo-data:
