version: '3.5'
services:
  db-catalog:
    image: mongo
    restart: always
    ports:
      - 30000:27017
    volumes:
      - mongo-data:/data/db
  catalog-ws:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:7000
    depends_on:
      - db-catalog
volumes:
  mongo-data:

