#logging.level.org.springframework.security.web.*=debug
server:
   port: 7000
   servlet:
      session:
         timeout: 21600s
spring:
   datasource:
      url: jdbc:h2:mem:userdb
      driverClassName: org.h2.Driver
      username: sa
      password: sa
   data:
      mongodb:
         host: localhost
         port: 27017
         database: catalog
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
         ddl-auto: update
   h2:
      console:
         enabled: true
         #path: /h2-console
         settings:
            web-allow-others: true
logging:
   level:
      org.springframework.security.web: debug